### ISSUE TITLE
Unexpectedly long runtime 

### ISSUE THREAD

**Issue by lemar1998** [krvoje/ca-bibd-generator#1]
Hi there, I followed your guide to build with sbt: assembly but it just takes forever to finish. It seems like the process automatically run some test cases with large BIBD parameters. How can I fix this?

**Comment by krvoje** [comment]
Hi, the description is outdated. You are better off looking directly at the code. These parameters are not really large, just the algorithm takes a long time to converge, and in some cases it doesn't. Try compiling without tests and doing some cases manually and see what happens.

Are you looking into this for a uni project?

**Comment by lemar1998** [comment]
Thanks for the reply! Yes I am looking into this for a uni project (kind of). Our research involves BIBD, I saw your project while I was developing my own on java. I tried to solve this with simulated annealing but it was stuck with local optima constantly. How do you evaluate the score/fitness of an incidence matrix? I think a better scoring function could probably solve the problem. 

Also, how do I actually compile without the test cases (Shame on me for not knowing fortran)?

**Comment by hperadin** [comment]
The Fortran code is an older version, you can safely ignore it and look at the Scala parts. 

The project runs on SBT so you just need to skip tests when doing assembly. The fitness part is in `MutationCABIBD.calculateChangeFactors`. I also had the local optima problem, I tried solving it by adding the "staleness" part, basically if the matrix stays unchanged for long enough it's going to change anyway. I got a cpl orders of magnitude improvement there, but it still gets stuck in larger matrices.

If you publish anything regarding this, feel free to send the link my way.

**Comment by krvoje** [comment]
The Fortran code is an older version, you can safely ignore it and look at the Scala parts.

The project runs on SBT so you just need to skip tests when doing assembly. The fitness part is in `MutationCABIBD.calculateChangeFactors`. I also had the local optima problem, I tried solving it by adding the "staleness" part, basically if the matrix stays unchanged for long enough it's going to change anyway. I got a cpl orders of magnitude improvement there, but it still gets stuck in larger matrices.

If you publish anything regarding this, feel free to send the link my way.

**Comment by lemar1998** [comment]
Sure! By the way, how exactly can I skip the tests? Is there a command to do that on SBT or do I have to modify the Makefile?

**Comment by krvoje** [comment]
The Makefile was there for the fortran project, and since that's obsolete I've removed it. The project is now hosted on Scala. 

I've updated the description, and removed the tests from the assembly build, if you didn't manage to make it work you can try it out now with `sbt "runMain..."`

**Comment by lemar1998** [comment]
Thanks! I made some modifications in the build file and one of the class in src and now it’s working properly.
I’ll still look at ur new description to make sure I’m not doing something terribly wrong.



在 2018年6月26日，下午5:47，krvoje <notifications@github.com<mailto:notifications@github.com>> 写道：


The Makefile was there for the fortran project, and since that's obsolete I've removed it. The project is now hosted on Scala.

I've updated the description, and removed the tests from the assembly build, if you didn't manage to make it work you can try it out now with sbt "runMain..."
